<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Reports.aspx.cs" Inherits="Reports" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ Register Assembly="ActiveReports.Web, Version=5.2.0.397, Culture=neutral, PublicKeyToken=cc4967777c49a3ff"
    Namespace="DataDynamics.ActiveReports.Web" TagPrefix="ActiveReportsWeb" %>


<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
   <link href="stylesheet.css" runat="server" rel="stylesheet"/> 
   <script src="jscript.js" language="javascript" type="text/javascript"></script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <center>
           <fieldset style="width: 893px; height: 272px"><legend><b><span style="color: #ffffff">Exam Details</span></b></legend>
                <table>
                    <tr>
                        <td style="height: 262px" valign="top">
                            <asp:GridView ID="gvExamDetails" runat="server" AllowPaging="True" AutoGenerateColumns="False"
                                CellPadding="5" CellSpacing="2"  PageSize="5" AutoGenerateDeleteButton="True"
                                AutoGenerateEditButton="True" OnPageIndexChanging="gvExamDetails_PageIndexChanging" OnRowCommand="gvExamDetails_RowCommand"  >
                                                 
                                <Columns>
                                   <asp:TemplateField HeaderText="Reports">
                                   <ItemTemplate>
                                   <asp:LinkButton ID="lnkReports" runat="Server" Text="Generate Reports"  CommandName="Reports"
                                    CommandArgument='<%#Eval("id") %>'></asp:LinkButton>
                                   </ItemTemplate>
                                   </asp:TemplateField>
                                   <asp:TemplateField HeaderText="View">
                                   <ItemTemplate>
                                   <asp:LinkButton ID="lnkView" runat="server" Text="View Reports" CommandName="ViewReports" CommandArgument='<%#Eval("id")%>'></asp:LinkButton>
                                   </ItemTemplate>
                                   </asp:TemplateField>
                                    <asp:TemplateField Visible="False">
                                        <ItemTemplate>
                                            <asp:Label ID="lblID" runat="Server" Text='<%#Eval("id")%>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Class">
                                        <ItemTemplate>
                                            <asp:Label ID="lblClass" runat="Server" Text='<%#Eval("class")%>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                 
                                    <asp:TemplateField HeaderText="Telugu">
                                        <ItemTemplate>
                                            <asp:Label ID="lblTelugu" runat="server" Text='<%#Eval("telugu")%>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Hindi">
                                        <ItemTemplate>
                                            <asp:Label ID="lblHindi" runat="server" Text='<%#Eval("hindi") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="English">
                                        <ItemTemplate>
                                            <asp:Label ID="lblEnglish" runat="server" Text='<%#Eval("english") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Maths">
                                        <ItemTemplate>
                                            <asp:Label ID="lblMaths" runat="server" Text='<%#Eval("maths") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Science">
                                        <ItemTemplate>
                                            <asp:Label ID="lblScience" runat="server" Text='<%#Eval("science") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Social">
                                        <ItemTemplate>
                                            <asp:Label ID="lblSocial" runat="server" Text='<%#Eval("social") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                                <PagerSettings FirstPageText="" LastPageText="" NextPageText="" PreviousPageText="" />
                                <RowStyle BackColor="#E0E0E0" />
                                <PagerStyle BackColor="Silver" ForeColor="Black" HorizontalAlign="Center" />
                                <HeaderStyle BackColor="#404040" ForeColor="White" />
                                <AlternatingRowStyle BackColor="#E0E0E0" />
                            </asp:GridView>
                        </td>
                    </tr>
                </table>
                
               </fieldset> 
                 <ActiveReportsWeb:WebViewer ID="webReports" runat="server" Height="379px" Width="923px" ViewerType="AcrobatReader">
             </ActiveReportsWeb:WebViewer>
            </center>
    </div>
    </form>
</body>
</html>
